# Generated by Django 5.2.8 on 2025-11-15 18:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='Group Name')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
                ('total_students', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Students')),
                ('participated_students', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Participated Students')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_professors', to='evaluations.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group-Professor Assignment',
                'verbose_name_plural': 'Group-Professor Assignments',
                'ordering': ['group', 'professor'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('department', models.CharField(max_length=200, verbose_name='Department')),
                ('groups', models.ManyToManyField(related_name='professors', through='evaluations.GroupProfessor', to='evaluations.group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='groupprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_groups', to='evaluations.professor', verbose_name='Professor'),
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q1: Clear syllabus with learning outcomes')),
                ('q2', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q2: Taught to stated outcomes')),
                ('q3', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q3: Arrived on time')),
                ('q4', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q4: Dismissed on time')),
                ('q5', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q5: Enthusiastic about content')),
                ('q6', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q6: Organized presentation')),
                ('q7', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q7: Helpful delivery method')),
                ('q8', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q8: Appropriate technology use')),
                ('q9', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q9: Knowledgeable about content')),
                ('q10', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q10: Accessible to students')),
                ('q11', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q11: Promoted critical thinking')),
                ('q12', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q12: Encouraged opposing viewpoints')),
                ('q13', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q13: Exemplified institutional values')),
                ('q14', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q14: Caring attitude toward students')),
                ('q15', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q15: Tests related to outcomes')),
                ('q16', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q16: Useful assignments')),
                ('q17', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q17: Useful textbook')),
                ('q18', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q18: Required learning resources')),
                ('q19', models.IntegerField(choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Q19: Access to sufficient resources')),
                ('q20_comment', models.TextField(blank=True, null=True, verbose_name='Q20: Additional comments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='evaluations.group', verbose_name='Group')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='evaluations.professor', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Survey Response',
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='groupprofessor',
            unique_together={('group', 'professor')},
        ),
    ]
