# Generated by Django 5.2.8 on 2025-11-15 18:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_departments_forward(apps, schema_editor):
    """Move data from department to department_old and create Department records"""
    Group = apps.get_model('evaluations', 'Group')
    Professor = apps.get_model('evaluations', 'Professor')
    Department = apps.get_model('evaluations', 'Department')
    
    # Collect unique department names
    department_names = set()
    for group in Group.objects.all():
        if group.department:
            department_names.add(group.department)
            group.department_old = group.department
            group.save()
    
    for professor in Professor.objects.all():
        if professor.department:
            department_names.add(professor.department)
            professor.department_old = professor.department
            professor.save()
    
    # Create Department records
    for dept_name in department_names:
        # Generate a simple code from the name
        code = ''.join(word[:3].upper() for word in dept_name.split()[:3])
        if not code:
            code = dept_name[:10].upper()
        
        Department.objects.get_or_create(
            name=dept_name,
            defaults={'code': code, 'description': f'Department of {dept_name}'}
        )
    
    # Link groups and professors to departments
    for group in Group.objects.all():
        if group.department_old:
            try:
                dept = Department.objects.get(name=group.department_old)
                group.department = dept
                group.save()
            except Department.DoesNotExist:
                pass
    
    for professor in Professor.objects.all():
        if professor.department_old:
            try:
                dept = Department.objects.get(name=professor.department_old)
                professor.department = dept
                professor.save()
            except Department.DoesNotExist:
                pass


def migrate_departments_reverse(apps, schema_editor):
    """Restore department CharField values from department_old"""
    Group = apps.get_model('evaluations', 'Group')
    Professor = apps.get_model('evaluations', 'Professor')
    
    for group in Group.objects.all():
        if group.department_old:
            group.department = group.department_old
            group.save()
    
    for professor in Professor.objects.all():
        if professor.department_old:
            professor.department = professor.department_old
            professor.save()


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        # Step 1: Create Department model
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        
        # Step 2: Rename old department fields
        migrations.RenameField(
            model_name='group',
            old_name='department',
            new_name='department_old',
        ),
        migrations.RenameField(
            model_name='professor',
            old_name='department',
            new_name='department_old',
        ),
        
        # Step 3: Add email field to professor
        migrations.AddField(
            model_name='professor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        
        # Step 4: Add new ForeignKey fields
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='evaluations.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professors', to='evaluations.department', verbose_name='Department'),
        ),
        
        # Step 5: Migrate data
        migrations.RunPython(migrate_departments_forward, migrate_departments_reverse),
    ]
