# Generated by Django 5.2.8 on 2025-11-15 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_department_group_department_old_and_more'),
    ]

    operations = [
        # Remove old department fields
        migrations.RemoveField(
            model_name='group',
            name='department_old',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='department_old',
        ),
        
        # Make department ForeignKey non-nullable
        migrations.AlterField(
            model_name='group',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='evaluations.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professors', to='evaluations.department', verbose_name='Department'),
        ),
    ]
