# Generated by Django 5.2.8 on 2025-11-18 16:42

import django.db.models.deletion
from django.db import migrations, models


def create_default_school(apps, schema_editor):
    """Create a default school for existing departments"""
    School = apps.get_model('evaluations', 'School')
    School.objects.create(
        id=1,
        name='Default University',
        code='DEFAULT',
        description='Default school for migration'
    )


def remove_default_school(apps, schema_editor):
    """Remove the default school"""
    School = apps.get_model('evaluations', 'School')
    School.objects.filter(id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_cleanup_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='School Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='School Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(create_default_school, remove_default_school),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['school__name', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Department Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Department Name'),
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='evaluations.school', verbose_name='School'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'code'), ('school', 'name')},
        ),
    ]
