# Generated by Django 4.2.26 on 2025-11-22 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_professor_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(verbose_name='Question Text (English)')),
                ('text_uz', models.TextField(verbose_name='Question Text (Uzbek)')),
                ('text_ru', models.TextField(verbose_name='Question Text (Russian)')),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-6)'), ('text', 'Text (Open-ended)')], default='rating', max_length=10, verbose_name='Question Type')),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Survey Question',
                'verbose_name_plural': 'Survey Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Survey Session', 'verbose_name_plural': 'Survey Sessions'},
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q1',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q11',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q12',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q13',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q14',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q15',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q16',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q17',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q18',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q19',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q2',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q20_comment',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q3',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q4',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q5',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q6',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q7',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q8',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='q9',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Rating Value')),
                ('text_value', models.TextField(blank=True, null=True, verbose_name='Text Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.question', verbose_name='Question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Survey Answer',
                'verbose_name_plural': 'Survey Answers',
                'ordering': ['question__order'],
                'unique_together': {('survey', 'question')},
            },
        ),
    ]
