# Generated by Django 4.2.26 on 2025-11-27 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_question_alter_survey_options_remove_survey_q1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(verbose_name='Question Text (English)')),
                ('text_uz', models.TextField(verbose_name='Question Text (Uzbek)')),
                ('text_ru', models.TextField(verbose_name='Question Text (Russian)')),
                ('question_type', models.CharField(choices=[('rating', 'Rating (1-6)'), ('text', 'Text Answer')], default='rating', max_length=10, verbose_name='Question Type')),
                ('order', models.IntegerField(default=0, help_text='Order in which this question appears', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, help_text='Only active questions will be shown in surveys', verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Internship Question',
                'verbose_name_plural': 'Internship Questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1 (1st year, Sep-Feb)'), (2, 'Semester 2 (1st year, Mar-May)'), (3, 'Semester 3 (2nd year, Sep-Feb)'), (4, 'Semester 4 (2nd year, Mar-May)'), (5, 'Semester 5 (3rd year, Sep-Feb)'), (6, 'Semester 6 (3rd year, Mar-May)'), (7, 'Semester 7 (4th year, Sep-Feb)'), (8, 'Semester 8 (4th year, Mar-May)')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Semester'),
        ),
        migrations.CreateModel(
            name='InternshipSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Completed At')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_surveys', to='evaluations.group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Internship Survey',
                'verbose_name_plural': 'Internship Surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, choices=[(1, 'Strongly Agree'), (2, 'Agree'), (3, 'Neither Agree nor Disagree'), (4, 'Disagree'), (5, 'Strongly Disagree'), (6, 'Not Applicable')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Rating Value')),
                ('text_value', models.TextField(blank=True, null=True, verbose_name='Text Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('internship_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_answers', to='evaluations.internshipsurvey', verbose_name='Internship Survey')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.internshipquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Internship Answer',
                'verbose_name_plural': 'Internship Answers',
                'ordering': ['question__order'],
                'unique_together': {('internship_survey', 'question')},
            },
        ),
    ]
